# The Makefile for ct-qmc project
#
# Type "Make ct-qmc" to get single-processor version
# Type "Make ct-qmc-mpi" to get multiple processor version

CPP= g++ -O3 -Wno-non-template-friend -Wno-write-strings
MPICPP = mpic++ -O3 -Wno-non-template-friend -Wno-write-strings

BIN = ${HOME}/bin
#Output Path

PART= -Dorb2
#Determines how many particles do we have

ZONE= -Dzone2
#Determines how many zones do we have

MPI = -Duse_mpi
#Determines whether we use mpi or not

CFLAGS = $(PART) $(ZONE)

default: ct-qmc-mpi

minictqmcworld.o : ../minictqmcworld.cpp ../minictqmcworld.h
	$(MPICPP) $(CXXFLAGS) $(INCLUDE) -c ../minictqmcworld.cpp 

ct-qmc: ct-qmc.cpp ../main.cpp ../ini.cpp
	$(CPP) $(CFLAGS) ct-qmc.cpp -o $(BIN)/ct-qmc

ct-qmc-mpi: ct-qmc.cpp ../main_mpi.cpp ../ini.cpp ../input.cpp minictqmcworld.o 
	$(MPICPP) $(CFLAGS) $(MPI) ct-qmc.cpp minictqmcworld.o -o $(BIN)/ct-qmc-mpi

change : ../change.cpp
	$(CPP) ../change.cpp -o ../change

clean:
	${RM} ct-qmc *.o

cleandata:
	cp _input.dat _input.dat.backup
	rm -f *.dat
	rm -f *.it*
	mv _input.dat.backup _input.dat





